name: "Set up wayland and wlroots libraries"
description: "Sets up the wayland and wlroots libraries for github workflows"
inputs:
  wayland-version:
    description: "Wayland library version to set up"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.wayland-version }}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: sudo setup-ubuntu.sh
      shell: bash
