on: [push]

jobs:
  release-versions:
    runs-on: ubuntu-22.04
    name: Set up release versions of libraries
    steps:
      - uses: actions/checkout@v3
      - uses: m-col/setup-wlroots-action@v0.1
        with:
          wayland-version: "1.22.0"
          wayland-protocols-version: "1.31"
          libdrm-version: "2.4.114"
          seatd-version: "0.6.4"
          pixman-version: "0.42.0"
          hwdata-version: "0.364"
          wlroots-version: "0.16.2"
      - run: echo "Done"
        shell: bash

  git-versions:
    runs-on: ubuntu-latest
    name: Set up git versions of libraries
    steps:
      - uses: actions/checkout@v3
      - uses: m-col/setup-wlroots-action@main
      - run: echo "Done"
        shell: bash
