on: [push]

jobs:
  dogfood:
    runs-on: ubuntu-latest
    name: Run the action
    steps:
      - uses: actions/checkout@v3
      - uses: m-col/setup-wlroots-action@v1.1
        with:
          wayland-version: "1.22.0"
      - run: echo "Done"
